language: node_js

node_js:
  - "stable"
  
os: osx

node_js:
  - 6

script:
  - yarn test
  - yarn build

cache:
  yarn: true
  directories:
    - node_modules
    
notifications:
  email:
    on_failure: change
    
